package com.wildodds.gymtracker.data.parser.smart

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Locks the current parsing behavior of [SmartXlsxParser] for the classic Wild Odds template
 * (W1D1 sheet naming + Program Info). Runs under Robolectric because the parser uses
 * android.util.Xml. Fixture: src/test/resources/fixtures/smart_classic.xlsx
 * (regenerated by make_fixture.py in the same directory).
 */
@RunWith(RobolectricTestRunner::class)
class SmartXlsxParserTest {

  @Test
  fun parsesClassicTemplate() {
  val input = javaClass.getResourceAsStream("/fixtures/smart_classic.xlsx")
  assertNotNull("fixture workbook is missing from test resources", input)

  val result = input!!.use { SmartXlsxParser().parse(it) }

  // Program-level fields come from the Program Info sheet.
  assertEquals("Test Strength Program", result.name)
  assertEquals(4, result.weeksDetected)
  assertEquals(Layout.VERTICAL, result.layoutDetected)
  assertTrue(
  "expected the classic-template detection path, got: ${result.weekDetectionMethod}",
  result.weekDetectionMethod.contains("W1D1")
  )

  // One day (W1D1) with two exercises in order.
  assertEquals(1, result.weekTemplate.size)
  val day = result.weekTemplate.first()
  assertEquals("Push Day", day.name)
  assertEquals("Chest, Shoulders", day.muscleGroups)
  assertEquals(2, day.exercises.size)

  val bench = day.exercises[0]
  assertEquals("Bench Press", bench.nameOriginal)
  assertTrue(bench.name.isNotBlank())
  assertEquals(3, bench.sets)
  assertEquals("8-10", bench.reps)
  assertEquals(60f, bench.weight!!, 0.001f)
  assertEquals(WeightUnit.KG, bench.weightUnit)
  assertEquals(0, bench.orderIndex)

  val ohp = day.exercises[1]
  assertEquals("Overhead Press", ohp.nameOriginal)
  assertEquals(3, ohp.sets)
  assertEquals("10", ohp.reps)
  assertEquals(40f, ohp.weight!!, 0.001f)
  assertEquals(1, ohp.orderIndex)
  }
}
