-- Verified Creator tier + creator marketplace. Written idempotently; apply via dashboard SQL Editor.
--
-- Money model (web-first / "Netflix-style"): Stripe Billing for the A$2/month Verified Creator
-- subscription, Stripe Connect Express destination charges for program sales with a 10% platform
-- application fee (creator keeps 90% minus processing). All purchases happen on the public
-- website — the Android app only READS entitlements (Google Play policy forbids external checkout
-- from inside the app; see docs/payments.md).
--
-- Writes to every table below happen ONLY via Edge Functions using the service-role key (the
-- stripe-webhook / publish-program functions). Clients get read-only, tightly-scoped SELECTs.

-- ── profiles: creator/billing columns ─────────────────────────────────────────
alter table public.profiles add column if not exists stripe_customer_id text;
alter table public.profiles add column if not exists stripe_connect_account_id text;
alter table public.profiles add column if not exists connect_onboarding_complete boolean not null default false;
-- Server-derived from creator_subscriptions.status by the stripe-webhook function on every
-- subscription event. Clients read it; only the service role ever writes it.
alter table public.profiles add column if not exists is_verified_creator boolean not null default false;
alter table public.profiles add column if not exists verified_since timestamptz;
alter table public.profiles add column if not exists creator_agreement_accepted_at timestamptz;
alter table public.profiles add column if not exists creator_agreement_version text;

-- ── creator_subscriptions ─────────────────────────────────────────────────────
create table if not exists public.creator_subscriptions (
  user_id uuid primary key references auth.users (id) on delete cascade,
  stripe_subscription_id text unique not null,
  status text not null,                      -- Stripe status verbatim: active/trialing/past_due/…
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.creator_subscriptions enable row level security;
drop policy if exists "creator_subscriptions_select_own" on public.creator_subscriptions;
create policy "creator_subscriptions_select_own" on public.creator_subscriptions
  for select using (user_id = auth.uid());
-- No insert/update/delete policies: service-role only.

-- ── marketplace_programs (listing metadata — safe to show publicly) ───────────
create table if not exists public.marketplace_programs (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  description text not null default '',
  price_cents integer not null check (price_cents between 100 and 50000),  -- A$1–A$500
  currency text not null default 'aud',
  status text not null default 'draft' check (status in ('draft', 'published', 'unpublished')),
  stripe_price_id text,                      -- optional; checkout uses ad-hoc price_data
  days_per_week integer not null default 0,
  total_weeks integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.marketplace_programs enable row level security;
create index if not exists idx_marketplace_programs_status on public.marketplace_programs (status, created_at);

-- Anyone (including signed-out storefront visitors) can browse PUBLISHED listings; creators see
-- their own rows in any status. The paid program content itself lives in a separate table below.
drop policy if exists "marketplace_programs_select" on public.marketplace_programs;
create policy "marketplace_programs_select" on public.marketplace_programs
  for select using (status = 'published' or creator_id = auth.uid());
-- No client writes: publishing goes through the publish-program Edge Function, which enforces
-- (active subscription) AND (Connect onboarding complete) AND (Creator Agreement accepted).

-- ── marketplace_program_content (the paid product — never public) ─────────────
create table if not exists public.marketplace_program_content (
  program_id bigint primary key references public.marketplace_programs (id) on delete cascade,
  program_json text not null                 -- ParsedProgram JSON, importable by the app
);
alter table public.marketplace_program_content enable row level security;
drop policy if exists "marketplace_content_select" on public.marketplace_program_content;
create policy "marketplace_content_select" on public.marketplace_program_content
  for select using (
    exists (select 1 from public.marketplace_programs mp
            where mp.id = program_id and mp.creator_id = auth.uid())
    or exists (select 1 from public.purchases p
               where p.program_id = marketplace_program_content.program_id
                 and p.buyer_id = auth.uid() and p.status = 'paid')
  );

-- ── purchases ────────────────────────────────────────────────────────────────
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references auth.users (id) on delete cascade,
  program_id bigint not null references public.marketplace_programs (id) on delete cascade,
  creator_id uuid not null references auth.users (id) on delete cascade,
  gross_amount_cents integer not null,
  platform_fee_cents integer not null,       -- 10% of gross, rounded half-up
  creator_earnings_cents integer not null,   -- gross − platform fee (Stripe processing comes out of this side)
  currency text not null default 'aud',
  stripe_payment_intent_id text unique not null,
  status text not null default 'paid' check (status in ('paid', 'refunded')),
  refunded_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.purchases enable row level security;
create index if not exists idx_purchases_buyer on public.purchases (buyer_id);
create index if not exists idx_purchases_creator on public.purchases (creator_id, created_at);
drop policy if exists "purchases_select_own" on public.purchases;
create policy "purchases_select_own" on public.purchases
  for select using (buyer_id = auth.uid() or creator_id = auth.uid());
-- No client writes: rows are created/updated only by the stripe-webhook function.

-- ── stripe_events (webhook idempotency ledger) ────────────────────────────────
create table if not exists public.stripe_events (
  id text primary key,                       -- Stripe event id (evt_…)
  type text not null,
  received_at timestamptz not null default now()
);
alter table public.stripe_events enable row level security;   -- no policies: service-role only

-- ── Public storefront identity (minimum columns, only for creators with a live listing) ──
-- The storefront must show a creator's name + verified badge to signed-out visitors, but the
-- profiles RLS (own row + friends) rightly blocks that. A security-definer view scoped to
-- creators with at least one PUBLISHED listing exposes exactly three columns, nothing else.
create or replace view public.creator_public as
  select p.id, p.username, p.is_verified_creator
  from public.profiles p
  where exists (select 1 from public.marketplace_programs mp
                where mp.creator_id = p.id and mp.status = 'published');
grant select on public.creator_public to anon, authenticated;

-- ── friends_of: also return the verified flag (badge next to names in friends lists) ──
drop function if exists public.friends_of(uuid);
create or replace function public.friends_of(other uuid)
returns table (id uuid, username text, is_verified_creator boolean)
language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.friends f where f.user_id = auth.uid() and f.friend_id = other) then
    raise exception 'not a friend';
  end if;
  return query
    select p.id, p.username, p.is_verified_creator from public.friends f
    join public.profiles p on p.id = f.friend_id
    where f.user_id = other;
end;
$$;
