-- Friends (social layer). Written idempotently; apply via the dashboard SQL Editor.
--
-- Model: a friendship is TWO rows in `friends` (one per direction), each owned by its user_id.
-- Befriending happens through redeem_friend_code() (security definer) so both rows appear
-- atomically. Cross-user visibility is deliberate and narrow:
--   * friends can read each other's profile SNAPSHOT (username, last session, PRs, achievements,
--     public program metadata) — published by the app, never raw training logs;
--   * friends can see each other's friends lists (an explicit product feature);
--   * events (motivation / flex / session_start / program shares) flow only between friends.

-- ── Profile snapshot columns (what friends may see) ───────────────────────────
alter table public.profiles add column if not exists friend_code text unique;
alter table public.profiles add column if not exists last_session_at bigint;          -- epoch ms
alter table public.profiles add column if not exists last_session_name text;
alter table public.profiles add column if not exists current_program text;
alter table public.profiles add column if not exists prs jsonb;                       -- {"squat":140,...}
alter table public.profiles add column if not exists achievements jsonb;              -- ["streak_7",...]
alter table public.profiles add column if not exists public_programs jsonb;           -- [{"name":..,"active":bool,"daysPerWeek":n}]
alter table public.profiles add column if not exists notify_on_friend_session boolean not null default false;

-- Friend codes for existing users + on signup.
update public.profiles set friend_code = upper(substr(md5(random()::text || id::text), 1, 8))
  where friend_code is null;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username, friend_code)
  values (new.id, null, upper(substr(md5(random()::text || new.id::text), 1, 8)));
  return new;
end;
$$;

-- ── friends ───────────────────────────────────────────────────────────────────
create table if not exists public.friends (
  user_id uuid not null references auth.users (id) on delete cascade,
  friend_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, friend_id),
  check (user_id <> friend_id)
);
alter table public.friends enable row level security;

-- RLS helper. SECURITY DEFINER (bypasses RLS) for two reasons:
--  * a friends policy that subqueries friends itself raises "infinite recursion detected
--    in policy" (42P17);
--  * a profiles/friend_events policy that subqueries friends would otherwise be filtered by
--    the CALLER's friends policy — checking "is X a friend of Y" against rows the caller
--    can't see always comes back false.
create or replace function public.are_friends(a uuid, b uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.friends f where f.user_id = a and f.friend_id = b);
$$;

-- Read: my own rows, plus my friends' rows (so I can view a friend's friends list).
drop policy if exists "friends_select" on public.friends;
create policy "friends_select" on public.friends
  for select using (
    user_id = auth.uid()
    or public.are_friends(auth.uid(), friends.user_id)
  );
-- Delete: I can remove MY direction of a friendship (unfriend severs my visibility; the RPC
-- below removes both). No direct insert/update — rows are created only via redeem_friend_code().
drop policy if exists "friends_delete_own" on public.friends;
create policy "friends_delete_own" on public.friends
  for delete using (user_id = auth.uid());

-- Profiles: let friends read each other's snapshot (owner policies from Phase 1 remain).
drop policy if exists "profiles_select_friends" on public.profiles;
create policy "profiles_select_friends" on public.profiles
  for select using (public.are_friends(profiles.id, auth.uid()));

-- ── friend_events (motivation / flex / session_start / program) ───────────────
create table if not exists public.friend_events (
  id bigint generated by default as identity primary key,
  sender uuid not null references auth.users (id) on delete cascade,
  recipient uuid not null references auth.users (id) on delete cascade,
  type text not null check (type in ('motivation', 'flex', 'session_start', 'program')),
  body text not null default '',
  created_at timestamptz not null default now(),
  notified boolean not null default false,  -- recipient device has posted a local notification
  seen boolean not null default false       -- recipient has viewed/acknowledged in-app
);
alter table public.friend_events enable row level security;
create index if not exists idx_friend_events_recipient on public.friend_events (recipient, seen, created_at);

drop policy if exists "friend_events_select_own" on public.friend_events;
create policy "friend_events_select_own" on public.friend_events
  for select using (recipient = auth.uid() or sender = auth.uid());

-- Send only as yourself, and only to a current friend.
drop policy if exists "friend_events_insert" on public.friend_events;
create policy "friend_events_insert" on public.friend_events
  for insert with check (
    sender = auth.uid()
    and public.are_friends(auth.uid(), recipient)
  );

-- Recipient may flip their own notified/seen flags.
drop policy if exists "friend_events_update_recipient" on public.friend_events;
create policy "friend_events_update_recipient" on public.friend_events
  for update using (recipient = auth.uid()) with check (recipient = auth.uid());

-- ── RPCs ──────────────────────────────────────────────────────────────────────

-- Redeem a friend code: creates the friendship BOTH ways. Security definer because the caller
-- can't insert the other user's row. Returns the new friend's user id.
create or replace function public.redeem_friend_code(code text)
returns uuid language plpgsql security definer set search_path = public as $$
declare target uuid;
begin
  select id into target from public.profiles where upper(friend_code) = upper(trim(code));
  if target is null then raise exception 'unknown friend code'; end if;
  if target = auth.uid() then raise exception 'that is your own code'; end if;
  insert into public.friends (user_id, friend_id) values (auth.uid(), target)
    on conflict do nothing;
  insert into public.friends (user_id, friend_id) values (target, auth.uid())
    on conflict do nothing;
  return target;
end;
$$;

-- Unfriend: removes BOTH directions (mine via policy, theirs via definer rights).
create or replace function public.unfriend(other uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  delete from public.friends where user_id = auth.uid() and friend_id = other;
  delete from public.friends where user_id = other and friend_id = auth.uid();
end;
$$;

-- Session-start fan-out: one 'session_start' event per friend who opted in
-- (profiles.notify_on_friend_session). Security definer so the sender needn't read recipients'
-- settings. The caller can only ever notify their OWN friends about themselves.
create or replace function public.notify_session_start(session_name text)
returns integer language plpgsql security definer set search_path = public as $$
declare cnt integer;
begin
  insert into public.friend_events (sender, recipient, type, body)
  select auth.uid(), f.friend_id, 'session_start', coalesce(session_name, '')
  from public.friends f
  join public.profiles p on p.id = f.friend_id
  where f.user_id = auth.uid() and p.notify_on_friend_session;
  get diagnostics cnt = row_count;
  return cnt;
end;
$$;

-- A friend's friends list (the "view their friends" feature) — usernames only, and only when the
-- caller is a friend of `other`. Security definer because friend-of-friend PROFILES are otherwise
-- (deliberately) unreadable; this exposes the minimum: id + username.
create or replace function public.friends_of(other uuid)
returns table (id uuid, username text) language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.friends f where f.user_id = auth.uid() and f.friend_id = other) then
    raise exception 'not a friend';
  end if;
  return query
    select p.id, p.username from public.friends f
    join public.profiles p on p.id = f.friend_id
    where f.user_id = other;
end;
$$;
